" -----------------------------------------------------------------------------
"  General
" -----------------------------------------------------------------------------

set nocompatible
set history=100
set encoding=utf8
set fileencoding=utf8

filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()


" -----------------------------------------------------------------------------
"  Backups
" -----------------------------------------------------------------------------

if has("vms")
    set nobackup                " do not keep a backup file, use versions instead
endif


" -----------------------------------------------------------------------------
"  UI
" -----------------------------------------------------------------------------

set number
set ruler               " show the cursor position all the time
set wildmenu
set wildmode=list:longest
set hlsearch
set scrolloff=3
set mouse=a
set backspace=indent,eol,start

set showcmd             " display incomplete commands
set incsearch           " do incremental searching
set hlsearch


" -----------------------------------------------------------------------------
"  Visual Cues
" -----------------------------------------------------------------------------

syntax on
colorscheme ir_black

" Set global color scheme.
let python_highlight_all = 1
if &term =~ '^\(xterm\|screen\)' && $TERM_PROGRAM != 'Apple_Terminal'
  set t_Co=256
endif
if &t_Co != 256
  let g:CSApprox_loaded=0
endif


" -----------------------------------------------------------------------------
"  Text Formatting
" -----------------------------------------------------------------------------
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set expandtab


" -----------------------------------------------------------------------------
"  Whitespace
" -----------------------------------------------------------------------------
highlight ExtraWhiteSpace ctermbg=red guibg=red
:match ExtraWhiteSpace /\s\+$\|\t\+/
match ExtraWhitespace /\s\+$\|\t\+/


" -----------------------------------------------------------------------------
"  Autocommands
" -----------------------------------------------------------------------------
" Only do this part when compiled with support for autocommands.
if has("autocmd")
    autocmd BufWritePre * :%s/\s\+$//e
    autocmd colorscheme * highlight ExtraWhitespace ctermbg=red guibg=red

    " Put these in an autocmd group, so that we can delete them easily.
    augroup vimrcEx
        au!

        " For all text files set 'textwidth' to 78 characters.
        autocmd FileType text setlocal textwidth=78

        " When editing a file, jump to the last known cursor position.
        autocmd BufReadPost *
                    \ if line("'\"") > 0 && line("'\"") <= line("$") |
                    \   exe "normal g`\"" |
                    \ endif
    augroup END
endif


" -----------------------------------------------------------------------------
"  Variables
" -----------------------------------------------------------------------------

let mapleader=","


" -----------------------------------------------------------------------------
"  Mappings
" -----------------------------------------------------------------------------

" working directory follows current file
map Q gq

" these require the NERD_comments modules
map ,c <leader>cl
map ,d <leader>cu

" execute file being edited with <Shift> + e:
map <buffer> <S-e> :w<CR>:!/usr/bin/env python % <CR>

" -----------------------------------------------------------------------------
"  Autocomplete
" -----------------------------------------------------------------------------

autocmd FileType python set omnifunc=pythoncomplete#Complete

" -----------------------------------------------------------------------------
"  TaskList
" -----------------------------------------------------------------------------

map T :TaskList<CR>


" -----------------------------------------------------------------------------
"  TagList
" -----------------------------------------------------------------------------

map S :TlistToggle<CR>
let Tlist_Ctags_Cmd='/usr/local/bin/ctags'
let Tlist_GainFocus_On_ToggleOpen = 1


" -----------------------------------------------------------------------------
"  NERDTree
" -----------------------------------------------------------------------------

nmap <silent> <c-n> :NERDTreeToggle<CR>
let NERDTreeIgnore          = ['\.pyc$','\.swp$']
let NERDTreeWinPos          = 'right'
let NERDTreeSplitVertical   = 1
let NERDTreeChDirMode       = 2
let NERDTreeShowBookmarks   = 1


" -----------------------------------------------------------------------------
"  Folding
" -----------------------------------------------------------------------------

map zz za
au BufWinLeave *.xul mkview
au BufWinEnter *.xul silent loadview
au BufWinLeave *.xml mkview
au BufWinEnter *.xml silent loadview
let javaScript_fold=1
